name: Bug Report
description: File a bug / issue
title: "bug: "
labels: [bug]
body:
  - type: input
    attributes:
      label: Neovim version (nvim -v)
      placeholder: 0.9.5
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: MacOS
    validations:
      required: true
  - type: input
    attributes:
      label: Terminal emulator / GUI
      placeholder: WezTerm
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A description of what the bug is. Please provide markdown as text in addition to screenshots & include any related errors you see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Healthcheck output
      description: Output of :checkhealth render-markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin configuration
      description: Your configuration for this plugin.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin error log
      description: Error log stored in vim.fn.stdpath(state)/render-markdown.log, typically ~/.local/state/nvim/render-markdown.log, if file is missing put N/A.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confirmations
      options:
      - label: I have provided markdown text for any screenshots used in my description & understand that my issue will be closed if I have not
        required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Any additional information you would like to provide.
    validations:
      required: false
